// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TingMusic
{

    public class SongList
    {

        [JsonProperty("artist_id")]
        public string ArtistId { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("pic_big")]
        public string PicBig { get; set; }

        [JsonProperty("pic_small")]
        public string PicSmall { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("area")]
        public string Area { get; set; }

        [JsonProperty("publishtime")]
        public string Publishtime { get; set; }

        [JsonProperty("album_no")]
        public string AlbumNo { get; set; }

        [JsonProperty("lrclink")]
        public string Lrclink { get; set; }

        [JsonProperty("copy_type")]
        public string CopyType { get; set; }

        [JsonProperty("hot")]
        public string Hot { get; set; }

        [JsonProperty("all_artist_ting_uid")]
        public string AllArtistTingUid { get; set; }

        [JsonProperty("resource_type")]
        public string ResourceType { get; set; }

        [JsonProperty("is_new")]
        public string IsNew { get; set; }

        [JsonProperty("rank_change")]
        public string RankChange { get; set; }

        [JsonProperty("rank")]
        public string Rank { get; set; }

        [JsonProperty("all_artist_id")]
        public string AllArtistId { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("del_status")]
        public string DelStatus { get; set; }

        [JsonProperty("relate_status")]
        public string RelateStatus { get; set; }

        [JsonProperty("toneid")]
        public string Toneid { get; set; }

        [JsonProperty("all_rate")]
        public string AllRate { get; set; }

        [JsonProperty("sound_effect")]
        public string SoundEffect { get; set; }

        [JsonProperty("file_duration")]
        public int FileDuration { get; set; }

        [JsonProperty("has_mv_mobile")]
        public int HasMvMobile { get; set; }

        [JsonProperty("versions")]
        public string Versions { get; set; }

        [JsonProperty("bitrate_fee")]
        public string BitrateFee { get; set; }

        [JsonProperty("song_id")]
        public string SongId { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("ting_uid")]
        public string TingUid { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("album_id")]
        public string AlbumId { get; set; }

        [JsonProperty("album_title")]
        public string AlbumTitle { get; set; }

        [JsonProperty("is_first_publish")]
        public int IsFirstPublish { get; set; }

        [JsonProperty("havehigh")]
        public int Havehigh { get; set; }

        [JsonProperty("charge")]
        public int Charge { get; set; }

        [JsonProperty("has_mv")]
        public int HasMv { get; set; }

        [JsonProperty("learn")]
        public int Learn { get; set; }

        [JsonProperty("song_source")]
        public string SongSource { get; set; }

        [JsonProperty("piao_id")]
        public string PiaoId { get; set; }

        [JsonProperty("korean_bb_song")]
        public string KoreanBbSong { get; set; }

        [JsonProperty("resource_type_ext")]
        public string ResourceTypeExt { get; set; }

        [JsonProperty("mv_provider")]
        public string MvProvider { get; set; }

        [JsonProperty("artist_name")]
        public string ArtistName { get; set; }
    }

    public class Billboard
    {

        [JsonProperty("billboard_type")]
        public string BillboardType { get; set; }

        [JsonProperty("billboard_no")]
        public string BillboardNo { get; set; }

        [JsonProperty("update_date")]
        public string UpdateDate { get; set; }

        [JsonProperty("havemore")]
        public int Havemore { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("comment")]
        public string Comment { get; set; }

        [JsonProperty("pic_s640")]
        public string PicS640 { get; set; }

        [JsonProperty("pic_s444")]
        public string PicS444 { get; set; }

        [JsonProperty("pic_s260")]
        public string PicS260 { get; set; }

        [JsonProperty("pic_s210")]
        public string PicS210 { get; set; }

        [JsonProperty("web_url")]
        public string WebUrl { get; set; }
    }

    public class BillList
    {

        [JsonProperty("song_list")]
        public SongList[] SongList { get; set; }

        [JsonProperty("billboard")]
        public Billboard Billboard { get; set; }

        [JsonProperty("error_code")]
        public int ErrorCode { get; set; }
    }

}
